# Generated by Django 3.0.4 on 2020-03-23 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_drug_advices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicesource',
            name='advice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='app.Advice'),
        ),
    ]
